apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-example
spec:
  selector:
    matchLabels:
      app: rest-example
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-example
        tier: backend
    spec:
      containers:
      - name: rest-example
        image: stigran/rest-example
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080